feat: add user creation endpoint
HijoDeHonor/game-store-be pull request #3
Opened 2024-06-26 11:44 UTC by HijoDeHonor

Implemented POST endpoint '/users' for user creation. Added corresponding Express routes and unit tests to verify functionality.

2024-06-26 11:57 UTC, PiewDev commented on server-with-mock.js
Is this duplicate file? is equal to that of sql

2024-06-26 11:59 UTC, PiewDev commented on test/user/userControler.test.js
don't use Magic Strings, uses constants

2024-06-26 12:00 UTC, PiewDev commented on test/user/userControler.test.js
Separate the test with comments:

Arrange
Act
Assert

2024-06-26 12:02 UTC, PiewDev commented on test/user/validationUser.test.js
don't use Magic Strings, uses constants.

Separate the test with comments:

Arrange
Act
Assert

2024-06-26 12:02 UTC, PiewDev commented on users/mockModel.js
Is this file necesary?

2024-06-26 12:04 UTC, PiewDev commented on users/mySqlModel.js
> +      await connection.query(
Needs an extra check on whether the user exists

2024-06-26 12:05 UTC, PiewDev commented on users/mySqlModel.js
> +const DEFAULT_CONFIG = {
Remove these configurations to a separate file

2024-06-26 12:06 UTC, HijoDeHonor commented on server-with-mock.js
no, this import the UserModel from another file to change if uses a MySQL o local files

2024-06-26 12:07 UTC, PiewDev commented on users/registerUser/userControler.js
> +    }
remove this try-catch should be handled by ErrorHandler

2024-06-26 12:09 UTC, PiewDev commented on users/registerUser/userControler.js
> +
Remove these class to a separate file

2024-06-26 12:15 UTC, PiewDev requested changes
It's pretty good, there are only small things to change.

2024-06-26 12:15 UTC, PiewDev commented on users/userSchema.js
> +
Remove this comments

2024-06-26 12:15 UTC, PiewDev commented on middlewares/errorHandler/errorhandler.js
> +
Are you importing this Constants?

2024-06-26 12:15 UTC, PiewDev commented on server-with-mock.js
Is this duplicate file? is equal to that of sql

2024-06-26 12:15 UTC, PiewDev commented on test/user/userControler.test.js
don't use Magic Strings, uses constants

Separate the test with comments:

Arrange
Act
Assert

2024-06-26 12:15 UTC, PiewDev commented on test/user/validationUser.test.js
Separate the test with comments:

Arrange
Act
Assert

2024-06-26 12:15 UTC, PiewDev commented on users/mockModel.js
Is this file necesary?

2024-06-26 12:15 UTC, PiewDev commented on users/mySqlModel.js
> +const DEFAULT_CONFIG = {
Remove these configurations to a separate file

2024-06-26 12:15 UTC, PiewDev commented on users/mySqlModel.js
> +      await connection.query(
Needs an extra check on whether the user exists

2024-06-26 12:15 UTC, PiewDev commented on users/registerUser/userControler.js
> +    }
remove this try-catch should be handled by ErrorHandler

2024-06-26 12:15 UTC, PiewDev commented on users/registerUser/userControler.js
> +
Remove these class to a separate file

2024-06-28 19:03 UTC, PiewDev requested changes
Very good, we need to make some small changes related to the health of the repository.

2024-06-28 19:03 UTC, PiewDev commented on package-lock.json
package.lock.json should not be saved to the repository

2024-06-28 19:03 UTC, PiewDev commented on package.json
> +    "sinon": "^18.0.0",
In the end you didn't use Sinon

2024-06-28 19:03 UTC, PiewDev commented on test/user/userControler.test.js
> +    expect(res.body).toEqual(uniqueUserName);
The response from the endpoint should be body.userName. make the change in the controller

2024-06-28 19:03 UTC, PiewDev commented on .vscode/settings.json
settings.json should not be saved to the repository

2024-06-28 22:29 UTC, PiewDev requested changes
A change that you missed from the previous one and a mistake of mine, we are even.

2024-06-28 22:29 UTC, PiewDev commented on .vscode/settings.json
Add to gitignore

2024-06-28 22:29 UTC, PiewDev commented on users/registerUser/userControler.js
> +      res.status(201).json({ userName: newUser });
My bad, the one that should return this format is the model.

2024-06-28 22:30 UTC, PiewDev commented on users/registerUser/userControler.js
> +      res.status(201).json({ userName: newUser });
newUser should be an object with the property userName

2024-07-01 11:22 UTC, PiewDev approved these changes
Good job! All the changes look good

2024-07-01 11:32 UTC, merged